"""UPI Sentinel Lakehouse - complete local Streamlit demonstration.

All records generated by this application are Synthetic Data only. This app
demonstrates a production-style Bronze/Silver/Gold fraud workflow locally with
pandas while showing the equivalent PySpark transformation.
"""

from __future__ import annotations

import pandas as pd
import streamlit as st


st.set_page_config(
    page_title="UPI Sentinel Lakehouse",
    page_icon="UPI",
    layout="wide",
    initial_sidebar_state="expanded",
)


def inject_styles() -> None:
    st.markdown(
        """
        <style>
        @import url('https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Space+Grotesk:wght@500;600;700&display=swap');
        html, body, [class*="css"] { font-family: 'DM Sans', sans-serif; }
        h1, h2, h3, h4 { font-family: 'Space Grotesk', sans-serif; color: #1f2937; }
        .block-container { padding-top: 1.5rem; padding-bottom: 3rem; max-width: 1500px; }
        .hero { background: linear-gradient(120deg, #667eea 0%, #764ba2 100%); border-radius: 24px; padding: 2.4rem 2.8rem; color: white; box-shadow: 0 18px 45px rgba(102,126,234,.28); margin-bottom: 1.6rem; }
        .hero h1 { color: white; font-size: clamp(2rem, 5vw, 3.45rem); letter-spacing: .08em; margin: 0; }
        .hero p { color: rgba(255,255,255,.88); font-size: 1.08rem; margin: .7rem 0 0; }
        .eyebrow { text-transform: uppercase; letter-spacing: .18em; font-size: .72rem; font-weight: 700; opacity: .82; }
        .tech-card, .layer-card, .metric-card { background: #f0f2f6; border-radius: 15px; padding: 1.1rem 1.2rem; min-height: 118px; box-shadow: 0 8px 22px rgba(15,23,42,.06); }
        .tech-icon { font-size: 1.9rem; margin-bottom: .35rem; }
        .tech-name { font-family: 'Space Grotesk', sans-serif; font-weight: 700; font-size: 1.03rem; color: #1f2937; }
        .tech-detail { color: #64748b; font-size: .8rem; margin-top: .3rem; }
        .metric-card { background: rgba(255,255,255,.84); border-left: 5px solid #667eea; min-height: 105px; }
        .metric-label { color: #64748b; font-size: .76rem; text-transform: uppercase; letter-spacing: .09em; font-weight: 700; }
        .metric-value { color: #1f2937; font-family: 'Space Grotesk', sans-serif; font-size: 1.85rem; font-weight: 700; margin-top: .35rem; }
        .metric-sub { color: #64748b; font-size: .78rem; margin-top: .2rem; }
        .layer-card { min-height: 185px; border-top: 5px solid #4ECDC4; background: white; }
        .layer-card h4 { margin: .4rem 0; }
        .layer-card p { color: #64748b; font-size: .87rem; line-height: 1.45; }
        .section-kicker { color: #667eea; text-transform: uppercase; font-size: .74rem; letter-spacing: .14em; font-weight: 700; margin-bottom: .35rem; }
        .status-pill { display: inline-block; border-radius: 999px; padding: .25rem .65rem; font-weight: 700; font-size: .75rem; }
        .status-live { color: #075e54; background: #d7f7f2; }
        .status-synthetic { color: #5b3a00; background: #fff4c2; }
        [data-testid="stMetric"] { background: white; border-radius: 15px; padding: 1rem; border-left: 5px solid #667eea; box-shadow: 0 8px 22px rgba(15,23,42,.06); }
        [data-testid="stTabs"] button { font-family: 'Space Grotesk', sans-serif; font-weight: 600; }
        </style>
        """,
        unsafe_allow_html=True,
    )


def metric_card(label: str, value: str, detail: str, color: str) -> None:
    st.markdown(
        f'<div class="metric-card" style="border-left-color:{color}">'
        f'<div class="metric-label">{label}</div><div class="metric-value">{value}</div>'
        f'<div class="metric-sub">{detail}</div></div>',
        unsafe_allow_html=True,
    )


@st.cache_data(show_spinner=False)
def generate_transactions() -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    """Create Bronze, Silver, and Gold Synthetic Data deterministically."""
    unique_count = 4980
    fraud_count = 250
    indexes = range(unique_count)
    timestamps = pd.date_range("2026-08-30 09:00:00", periods=unique_count, freq="17s")
    cities = ["Mumbai", "Bengaluru", "Delhi", "Hyderabad", "Pune", "Chennai"]
    merchant_categories = ["Retail", "Food", "Travel", "Utilities", "Gaming", "Healthcare"]

    base = pd.DataFrame(
        {
            "txn_id": [f"TXN-{i:08d}" for i in indexes],
            "upi_id": [f"user{i % 850:04d}@syntheticupi" for i in indexes],
            "amount": [float((i * 7919) % 34991 + 10) for i in indexes],
            "timestamp": timestamps,
            "payer_location": [cities[i % len(cities)] for i in indexes],
            "payee_location": [cities[i % len(cities)] for i in indexes],
            "device_change_flag": [False if i % 9 else True for i in indexes],
            "txn_velocity_per_hour": [(i * 7) % 9 + 1 for i in indexes],
            "merchant_category": [merchant_categories[i % len(merchant_categories)] for i in indexes],
        }
    )

    fraud_indexes = list(range(0, fraud_count * 3, 3))
    base.loc[fraud_indexes, "amount"] = [40001 + (i % 9999) for i in fraud_indexes]
    base.loc[fraud_indexes, "txn_velocity_per_hour"] = [11 + (i % 8) for i in fraud_indexes]
    base.loc[fraud_indexes, "payer_location"] = "Mumbai"
    base.loc[fraud_indexes, "payee_location"] = "Delhi"
    base.loc[fraud_indexes, "device_change_flag"] = True

    bronze = pd.concat([base, base.iloc[:20].copy()], ignore_index=True)
    silver = bronze.drop_duplicates(subset=["txn_id"], keep="first").copy()
    silver["timestamp"] = pd.to_datetime(silver["timestamp"])
    silver["fraud_flag"] = (
        silver["amount"].gt(40000)
        & silver["txn_velocity_per_hour"].gt(10)
        & silver["payer_location"].ne(silver["payee_location"])
    )
    silver["risk_score"] = silver["fraud_flag"].map({True: 100, False: 5}).astype(int)
    silver["fraud_reason"] = silver["fraud_flag"].map(
        {True: "High amount + velocity + location mismatch", False: "No rule triggered"}
    )
    gold = silver[silver["fraud_flag"]].copy()
    return bronze, silver, gold


def spark_etl_code() -> str:
    return '''from pyspark.sql import functions as F

# Bronze: ingest raw Synthetic Data and retain ingestion metadata.
bronze = spark.read.json("/mnt/upi/bronze/*.json")

# Silver: deduplicate transactions and standardize analytical columns.
silver = (bronze
    .dropDuplicates(["txn_id"])
    .withColumn("amount", F.col("amount").cast("double"))
    .withColumn("timestamp", F.to_timestamp("timestamp"))
    .withColumn("_is_valid", F.col("upi_id").isNotNull())
)

# Gold: transparent rule-based fraud flag for analytics.
gold = (silver
    .withColumn("fraud_flag",
        (F.col("amount") > 40000) &
        (F.col("txn_velocity_per_hour") > 10) &
        (F.col("payer_location") != F.col("payee_location")))
    .withColumn("risk_score", F.when(F.col("fraud_flag"), 100).otherwise(5))
)
gold.write.format("delta").mode("overwrite").saveAsTable("gold.fraud_transactions")'''


def styled_fraud_table(gold: pd.DataFrame):
    columns = ["txn_id", "upi_id", "amount", "timestamp", "payer_location", "payee_location", "risk_score"]
    return (
        gold[columns].head(25).style
        .format({"amount": "{:,.2f}"})
        .set_properties(**{"background-color": "#fff1f1", "color": "#991b1b"})
    )


def render_step_1() -> None:
    st.markdown(
        '<div class="hero"><div class="eyebrow">Synthetic Data Engineering Control Plane</div>'
        '<h1>UPI SENTINEL LAKEHOUSE</h1>'
        '<p>Real-time Fraud Monitoring | Medallion Lakehouse | Data Engineer 1.3 Yrs</p></div>',
        unsafe_allow_html=True,
    )
    st.markdown('<div class="section-kicker">Step 1 / Platform foundation</div>', unsafe_allow_html=True)
    cards = [
        ("🐍", "Python", "Simulation, orchestration, validation", "#667eea"),
        ("⚡", "PySpark", "Distributed ETL and fraud rules", "#764ba2"),
        ("◈", "Databricks Delta Lake", "ACID Bronze/Silver/Gold storage", "#4ECDC4"),
        ("✓", "ETL Testing", "Quality gates and anomaly checks", "#FF6B6B"),
    ]
    columns = st.columns(4)
    for column, (icon, name, detail, color) in zip(columns, cards):
        with column:
            st.markdown(
                f'<div class="tech-card" style="border-top:4px solid {color}">'
                f'<div class="tech-icon">{icon}</div><div class="tech-name">{name}</div>'
                f'<div class="tech-detail">{detail}</div></div>',
                unsafe_allow_html=True,
            )


def render_step_2(bronze: pd.DataFrame, silver: pd.DataFrame, gold: pd.DataFrame) -> None:
    st.markdown('<div class="section-kicker">Step 2 / Medallion architecture flow</div>', unsafe_allow_html=True)
    st.graphviz_chart(
        '''digraph {
            graph [bgcolor="transparent", rankdir=LR, pad="0.2"];
            node [shape=box, style="rounded,filled", fontname="Arial", fontsize=14, margin="0.22,0.16", color="#ffffff"];
            edge [color="#64748b", penwidth=2, arrowsize=.8];
            Bronze [label="BRONZE\\nRaw UPI JSON", fillcolor="#FF6B6B", fontcolor="white"];
            Silver [label="SILVER\\nCleaned & Deduped", fillcolor="#4ECDC4", fontcolor="#123b3a"];
            Gold [label="GOLD\\nFraud Flagged", fillcolor="#FFE66D", fontcolor="#5b4b00"];
            Dashboard [label="DASHBOARD", fillcolor="#667eea", fontcolor="white"];
            Bronze -> Silver -> Gold -> Dashboard;
        }''',
        use_container_width=True,
    )
    layers = [
        ("BRONZE", "Raw landing zone", len(bronze), "Ingested Synthetic Data, including the 20 duplicate records used for the quality demonstration.", "#FF6B6B"),
        ("SILVER", "Quality and deduplication", len(silver), "Standardized fields and one record per txn_id after the Silver quality gate.", "#4ECDC4"),
        ("GOLD", "Risk-ready analytics", len(gold), "Transactions matching the high-amount, high-velocity, location-mismatch fraud rule.", "#FFE66D"),
    ]
    columns = st.columns(3)
    for column, (name, subtitle, count, detail, color) in zip(columns, layers):
        with column:
            st.markdown(
                f'<div class="layer-card" style="border-top-color:{color}">'
                f'<div class="section-kicker">{name}</div><h4>{subtitle}</h4>'
                f'<div class="metric-value">{count:,}</div><p>{detail}</p></div>',
                unsafe_allow_html=True,
            )


def render_step_3(bronze: pd.DataFrame, silver: pd.DataFrame, gold: pd.DataFrame) -> None:
    st.markdown('<div class="section-kicker">Step 3 / Data simulation and PySpark ETL</div>', unsafe_allow_html=True)
    st.info("Synthetic Data only: 5,000 Bronze events are generated in memory, including 20 duplicate txn_id values. The local transformation uses pandas; the code below shows the PySpark/Delta equivalent.")
    left, right = st.columns([1.1, 1])
    with left:
        st.subheader("Live Bronze -> Silver -> Gold transformation")
        st.dataframe(
            pd.DataFrame(
                {"layer": ["Bronze", "Silver", "Gold"], "records": [len(bronze), len(silver), len(gold)], "operation": ["Raw load", "Deduplicate txn_id", "Apply fraud rule"]}
            ),
            use_container_width=True,
            hide_index=True,
        )
        st.caption("The transformation is deterministic so every browser refresh produces the same interview-ready result.")
    with right:
        st.subheader("PySpark implementation")
        st.code(spark_etl_code(), language="python")


def render_step_4(bronze: pd.DataFrame, silver: pd.DataFrame, gold: pd.DataFrame) -> None:
    st.markdown('<div class="section-kicker">Step 4 / ETL testing suite</div>', unsafe_allow_html=True)
    st.subheader("Automated quality gates")
    duplicate_count = len(bronze) - len(silver)
    results = st.columns(4)
    with results[0]:
        st.warning(f"Count Validation\n\nBronze {len(bronze):,} vs Silver {len(silver):,}")
    with results[1]:
        st.success("Null Check\n\nPASS - upi_id has no null values")
    with results[2]:
        st.error(f"Duplicate Check\n\n{duplicate_count} duplicate txn_id values removed")
    with results[3]:
        st.success(f"Fraud Logic Validation\n\nPASS - {len(gold):,} expected flags found")
    st.subheader("Flagged fraud transactions")
    st.dataframe(styled_fraud_table(gold), use_container_width=True, hide_index=True)


def render_step_5(silver: pd.DataFrame, gold: pd.DataFrame) -> None:
    st.markdown('<div class="section-kicker">Step 5 / Fraud analytics dashboard</div>', unsafe_allow_html=True)
    fraud_amount = gold["amount"].sum()
    fraud_rate = len(gold) / len(silver) * 100
    cards = st.columns(4)
    with cards[0]:
        metric_card("Total Transactions", f"{len(silver):,}", "Silver deduplicated volume", "#667eea")
    with cards[1]:
        metric_card("Fraud Count", f"{len(gold):,}", "High-risk transactions", "#FF6B6B")
    with cards[2]:
        metric_card("Fraud Amount", f"₹{fraud_amount:,.0f}", "Synthetic flagged value", "#FFE66D")
    with cards[3]:
        metric_card("Fraud Rate", f"{fraud_rate:.2f}%", "Rule-based detection rate", "#4ECDC4")

    left, right = st.columns(2)
    with left:
        st.subheader("Fraud amount by location")
        st.bar_chart(gold.groupby("payer_location")["amount"].sum().sort_values(ascending=False))
    with right:
        st.subheader("Fraud transaction timeline")
        daily = gold.assign(date=gold["timestamp"].dt.date).groupby("date").size().rename("fraud_transactions")
        st.area_chart(daily)


def render_step_6(gold: pd.DataFrame) -> None:
    st.markdown('<div class="section-kicker">Step 6 / Real-time monitoring and controls</div>', unsafe_allow_html=True)
    st.subheader("Operations control room")
    status_left, status_mid, status_right = st.columns(3)
    with status_left:
        st.markdown('<span class="status-pill status-live">PIPELINE HEALTHY</span>', unsafe_allow_html=True)
        st.caption("Synthetic event stream processed")
    with status_mid:
        st.markdown('<span class="status-pill status-synthetic">SYNTHETIC DATA</span>', unsafe_allow_html=True)
        st.caption("No real banking or customer data")
    with status_right:
        st.markdown('<span class="status-pill status-live">DELTA READY</span>', unsafe_allow_html=True)
        st.caption("Gold output is dashboard-ready")

    recent = gold.sort_values("timestamp", ascending=False).head(12).copy()
    recent["timestamp"] = recent["timestamp"].dt.strftime("%Y-%m-%d %H:%M:%S")
    recent["alert"] = "REVIEW"
    st.subheader("Latest high-risk event queue")
    st.dataframe(
        recent[["txn_id", "timestamp", "upi_id", "amount", "payer_location", "payee_location", "risk_score", "alert"]],
        use_container_width=True,
        hide_index=True,
    )
    st.caption("Refresh the Streamlit page to replay the deterministic local event stream. For production streaming, use the Bronze Auto Loader notebook and Delta tables in Databricks.")


def main() -> None:
    inject_styles()
    bronze, silver, gold = generate_transactions()
    st.sidebar.markdown("### UPI Sentinel")
    st.sidebar.caption("Local portfolio control plane")
    st.sidebar.metric("Synthetic events", f"{len(bronze):,}")
    st.sidebar.metric("Fraud alerts", f"{len(gold):,}")
    st.sidebar.caption("Run with: python -m streamlit run app.py")

    steps = st.tabs(
        [
            "STEP 1 - HEADER & TECH STACK",
            "STEP 2 - MEDALLION ARCHITECTURE FLOW",
            "STEP 3 - DATA SIMULATION & PYSPARK ETL",
            "STEP 4 - ETL TESTING SUITE",
            "STEP 5 - FRAUD ANALYTICS DASHBOARD",
            "STEP 6 - REAL-TIME MONITORING",
        ]
    )
    with steps[0]:
        render_step_1()
    with steps[1]:
        render_step_2(bronze, silver, gold)
    with steps[2]:
        render_step_3(bronze, silver, gold)
    with steps[3]:
        render_step_4(bronze, silver, gold)
    with steps[4]:
        render_step_5(silver, gold)
    with steps[5]:
        render_step_6(gold)


if __name__ == "__main__":
    main()
